### ISSUE TITLE
Retrieving credentials returns an error

### ISSUE THREAD

**Issue by monteluth** [schubergphilis/towerlib#27]
Snippet of code to retrieve credentials:

  for credential in tower.credentials:
    print(credential.name);

Returns the following error:

Traceback (most recent call last):
  File "./tower.py", line 280, in <module>
    GatherCredentialInfo(tower)
  File "./tower.py", line 22, in GatherCredentialInfo
    for credential in tower.credentials:
  File "/home/mrloth/VPython/lib/python2.7/site-packages/towerlib/entities/core.py", line 322, in _get_entity_objects
    yield entity_object(self._tower, data)
TypeError: this constructor takes no arguments

**Comment by dogfish182** [comment]
I've just verified that this issue does not present with latest package version 2.3.6 and a python 3.7.x environment, can you try that?

**Comment by dogfish182** [comment]
Closing this for now.
