### ISSUE TITLE
TypeError: Object of type User is not JSON serializable

### ISSUE THREAD

**Issue by sylvainmouquet** [schubergphilis/towerlib#72]
Hello,

We use towerlib with flask project. An endpoint returns a user object but we have an error because the object User is not serializable.

A quick example : 
```
$ from towerlib.entities import User
$ import json
$ user = User(None, None)
$ json.dumps(user)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
```

Do you have a solution to expose a User object in json ?

**Comment by sylvainmouquet** [comment]
i have changed the code it's not still necessary
